# Generated by Django 3.0 on 2023-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('productdescription', models.CharField(max_length=255)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productimage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
