# Generated by Django 3.0 on 2023-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=255)),
                ('customeremail', models.CharField(max_length=255)),
                ('customeraddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
