# Generated by Django 3.0 on 2023-11-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('orderdetailid', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.orders')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.products')),
            ],
        ),
    ]
