# Generated by Django 3.0 on 2023-11-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('reviewid', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.products')),
            ],
        ),
    ]
